-- AlterTable
ALTER TABLE `VisitEvent` ADD COLUMN `blocked_reason` VARCHAR(255) NULL,
    ADD COLUMN `status` ENUM('DRAFT', 'READY_BPJS', 'BLOCKED_BPJS', 'SENT_BPJS', 'FAILED_BPJS') NOT NULL DEFAULT 'DRAFT';
